import { Genre } from "./migoTypes";

export const fakeGenreList: Genre[] = [
    { id: 0, name: 'action'},
    { id: 1, name: 'adventure'},
    { id: 2, name: 'comedy'},
    { id: 3, name: 'demons'},
    { id: 4, name: 'drama'},
    { id: 5, name: 'ecchi'},
    { id: 6, name: 'fantasy'},
    { id: 7, name: 'harem'},
    { id: 8, name: 'h'},
    { id: 9, name: 'historical'},
    { id: 10, name: 'horror'},
    { id: 11, name: 'romance'},
    { id: 12, name: 'magic'},
    { id: 13, name: 'martial arts'},
    { id: 14, name: 'mecha'},
    { id: 15, name: 'military'},
    { id: 16, name: 'music'},
    { id: 17, name: 'mystery'},
    { id: 18, name: 'psycological'},
    { id: 19, name: 'school'},
    { id: 20, name: 'sci-fi'},
    { id: 21, name: 'slice of life'},
    { id: 22, name: 'sports'},
    { id: 23, name: 'super power'},
    { id: 24, name: 'supernatural'},
    { id: 25, name: 'game'},
    { id: 26, name: 'vampire'},
    { id: 27, name: 'yaoi'},
    { id: 28, name: 'yuri'},
];
